const employeeData = [
  { id: 1, Name: "Burg", email: "bhatherley0@nature.com", gender: "Male" },
  { id: 2, Name: "Franky", email: "fpeeke1@tinypic.com", gender: "Male" },
  {
    id: 3,
    Name: "Brewer",
    email: "bmonk2@chicagotribune.com",
    gender: "Non-binary",
  },
  { id: 4, Name: "Urbain", email: "uskyrme3@fc2.com", gender: "Male" },
  { id: 5, Name: "Babbette", email: "berdes4@gov.uk", gender: "Female" },
  { id: 6, Name: "Lawton", email: "lfabbro5@census.gov", gender: "Polygender" },
  { id: 7, Name: "Corene", email: "crudwell6@wufoo.com", gender: "Female" },
  { id: 8, Name: "Cointon", email: "cleffek7@i2i.jp", gender: "Male" },
  { id: 9, Name: "Sharline", email: "sruppele8@reuters.com", gender: "Female" },
  { id: 10, Name: "Kacie", email: "kvenus9@163.com", gender: "Female" },
  { id: 11, Name: "Toddy", email: "tstonesa@tripod.com", gender: "Male" },
  {
    id: 12,
    Name: "Torrie",
    email: "tbaumlerb@sourceforge.net",
    gender: "Female",
  },
  { id: 13, Name: "Nerty", email: "nbosquetc@dyndns.org", gender: "Female" },
  { id: 14, Name: "Missie", email: "mgommd@vk.com", gender: "Female" },
  { id: 15, Name: "Megen", email: "mbrasiere@addthis.com", gender: "Female" },
  {
    id: 16,
    Name: "Bobbie",
    email: "btaylderf@themeforest.net",
    gender: "Female",
  },
  { id: 17, Name: "Abbie", email: "aotimonyg@webnode.com", gender: "Female" },
  {
    id: 18,
    Name: "Marguerite",
    email: "mhamsharh@symantec.com",
    gender: "Female",
  },
  { id: 19, Name: "Matthias", email: "mdearnaleyi@ihg.com", gender: "Male" },
  { id: 20, Name: "Susette", email: "sgarryj@goo.ne.jp", gender: "Female" },
  { id: 21, Name: "Selie", email: "swalbrunk@usda.gov", gender: "Genderqueer" },
  { id: 22, Name: "Kev", email: "kwilsel@nih.gov", gender: "Male" },
  {
    id: 23,
    Name: "Ermin",
    email: "eyashinm@hatena.ne.jp",
    gender: "Genderfluid",
  },
  { id: 24, Name: "Suzie", email: "spoagn@hud.gov", gender: "Female" },
  { id: 25, Name: "Isaac", email: "ivondrako@sfgate.com", gender: "Male" },
  { id: 26, Name: "Levey", email: "lwhitehurstp@ocn.ne.jp", gender: "Male" },
  {
    id: 27,
    Name: "Fidelity",
    email: "fbulleynq@hugedomains.com",
    gender: "Female",
  },
  { id: 28, Name: "Carin", email: "cmarshamr@wikimedia.org", gender: "Female" },
  { id: 29, Name: "Inga", email: "istuttards@a8.net", gender: "Female" },
  {
    id: 30,
    Name: "Forest",
    email: "fcapehornt@dailymotion.com",
    gender: "Male",
  },
];

export default employeeData;
